#!/bin/sh
#
# (c) 2019 Bjorn Fischer, CeBiTec, Bielefeld University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

checkUser() {
    for pid in `pgrep -u $1`; do
        if fgrep -qs "cpu,cpuacct:/user/$user" /proc/$pid/cgroup; then
            [ x$verbose = xyes ] && \
                echo + $2 "[$pid]" `head -c 70 /proc/$pid/cmdline`
        else
            echo - $2 "[$pid]" `head -c 70 /proc/$pid/cmdline`
            stray=yes
        fi
    done
}

while getopts avh opt; do
    case $opt in
        a)
            all=yes
            ;;
        v)
            verbose=yes
            ;;
        *)
            echo List stray processes, i.e. processes that are not confined in a cgroup.
            echo Usage:  ${0##*/} '[-v] [-a | <username>]'
            echo '       -v also report confined processes'
            echo '       -a list stray processes for all users'
            echo '       If neither -a nor <username> is given list stray processes'
            echo '           of current user.'
            exit
    esac
done
shift `expr $OPTIND - 1`

if [ x$all = xyes ]; then
    #
    # check all logged in users
    #
    for user in `w -uhso | awk '{print $1}' | sort -u`; do
        checkUser $user $user
    done
    [ x$stray = x -a x$verbose = x ] && echo No stray processes found.
    exit;
fi

if [ x$1 = x ]; then
    user=$LOGNAME
else
    if id $1 >/dev/null 2>&1; then
        user=$1
    else
        echo No such user: $1
        exit 1
    fi
fi

checkUser $user
[ x$stray = x -a x$verbose = x ] && echo No stray processes found.

